name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Dar permissão ao gradlew
        run: chmod +x 01.WebViewStarterTemplate/gradlew

      - name: Build Debug APK
        run: |
          cd 02. ArtUi
          ./gradlew assembleDebug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: Mulher-Amparada-debug
          path: 01.WebViewStarterTemplate/app/build/outputs/apk/debug/*.apk

      - name: Build Release APK
        run: |
          cd 02. ArtUi
          ./gradlew assembleRelease

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: Mulher-Amparada-release
          path: 01.WebViewStarterTemplate/app/build/outputs/apk/release/*.apk
